package sandbox.inacio.maven.generator.question;

public enum QuestionId {
	PARENT_PROJECT_GROUP_ID,
	PARENT_PROJECT_NAME,
	PARENT_PROJECT_VERSION,	
	EJB_MODULE_NAME,
	EJB_PERSISTENCE_UNIT_NAME,
	CLIENT_MODULE_NAME,
}
